name: Ans Test / Windows

on:
 workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3.1.0

      - name: Set up Python 3
        uses: actions/setup-python@v4.2.0
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ansible==7.0.0

      - name: Run Ansible playbook
        uses: dawidd6/action-ansible-playbook@v2.6.1
        with:
          playbook: ./divona_windows.yml
          directory: ./
          requirements: divona/requirements-windows.yml
          inventory: |
            [all]
            localhost

            [all:vars]
            env=windows
          options: |
            -c local
            --verbose
