# This is a basic workflow to help you get started with Actions

name: EMU2

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  run-emulator:
    runs-on: macos-12
  
    steps: 
    
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Setup Android SDK
      uses: android-actions/setup-android@v2
      
    - name: Setup gradle
      uses: gradle/gradle-build-action@v2    
        
    - name: Create Android emulator
      run: |
        # install the hardware acceleration
        echo " Installing Hardware Acceleration Manager..."
        brew install intel-haxm
        sysctl kern.hv_support
        sdkmanager --install "system-images;android-31;google_apis;x86_64"
        echo "no" | avdmanager --verbose create avd --force --name TestAvd123 --package 'system-images;android-31;google_apis;x86_64'
        echo "AVD created:"
        "$ANDROID_HOME/emulator/emulator" -list-avds
          
        echo "Starting the Android emulator..."
        export ANDROID_EMULATOR_DEBUG=1
        nohup "$ANDROID_HOME/emulator/emulator" -avd TestAvd123 -gpu host -no-snapshot-load 2>&1 &
        $ANDROID_HOME/platform-tools/adb wait-for-device
        echo "Emulator has finished booting"
        $ANDROID_HOME/platform-tools/adb devices
        sleep 45
        screencapture screenshot.jpg
        $ANDROID_HOME/platform-tools/adb exec-out screencap -p > emulator.png
          
    - name: install recorder and record session
      run: |
          brew install ffmpeg
          $ANDROID_HOME/tools/emulator -port 18725 -verbose -accel on -no-audio -gpu host @TestAvd123 &
          ffmpeg -f avfoundation -i 0 -t 45 out.mov
          # node -e "const exec = require('child_process'); exec.exec('ffmpeg -f avfoundation -i 0 -t 120 out.mov'); exec.exec('$ANDROID_HOME/tools/emulator -port 18725 -verbose -no-window -no-audio -gpu swiftshader_indirect @TestAvd123 &');"
      env:
           HOMEBREW_NO_INSTALL_CLEANUP: 1
          
    - name: upload video
      uses: actions/upload-artifact@master
      with:
            name: out
            path: out.mov
             
    - uses: actions/upload-artifact@v3
      with:
           name: screenshot.jpg
           path: screenshot.jpg
             
    - uses: actions/upload-artifact@v3
      with:
           name: emulator.png
           path: emulator.png
