# This is a basic workflow to help you get started with Actions

name: android-emulator-test-macos

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  run-emulator:
    runs-on: macos-12
  
    steps: 
       - name: Create Android emulator
         run: |
          brew install intel-haxm
