name: GHCuptest

on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  macos:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - name: test ghcup
        run: |
         function Take-Part {
         param (
         [Parameter(ValueFromPipeline)]
         [string] $toolOutput,
         [string] $Delimiter = " ",
         [int[]] $Part
         )
         $parts = $toolOutput.Split($Delimiter, [System.StringSplitOptions]::RemoveEmptyEntries)
         $selectedParts = $parts[$Part]
         return [string]::Join($Delimiter, $selectedParts)
         }
         
         function Run-Command {
         param (
         [Parameter(Mandatory=$true)]
         [string] $Command,
         [switch] $SuppressStderr
         )
         # Bash trick to suppress and show error output because some commands write to stderr (for example, "python --version")
         $redirectOutputArguments = If ($SuppressStderr) { "2> /dev/null" } Else { "2>&1" }
         $stdout = & bash -c "${Command} ${redirectOutputArguments}"
         return $stdout
         }
         
         $ghcUpVersion = Run-Command "ghcup --version" | Take-Part -Part 5 
         return "GHCup $ghcUpVersion"
         
      
        shell: pwsh
