# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macOS-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Install emulator and create avd
        run: |
          echo '----------Install Emulator--------------'
          $ANDROID_HOME/tools/bin/sdkmanager --install emulator
          $ANDROID_HOME/emulator/emulator -version
          echo '----------Download Images--------------'
          $ANDROID_HOME/tools/bin/sdkmanager "system-images;android-30;default;x86_64"
          echo '----------Create AVD--------------'
          $ANDROID_HOME/tools/bin/avdmanager create avd -n Pixel_5_API_31 -d pixel --package "system-images;android-31;default;x86_64"
          echo '----------Show Available Emulators--------------'
          $ANDROID_HOME/emulator/emulator -list-avds
          echo '----------Start adb server--------------'
          $ANDROID_HOME/platform-tools/adb start-server
          # echo '----------Start Emulator--------------'
          # $ANDROID_HOME/tools/emulator -port 18725 -verbose -no-audio -gpu swiftshader_indirect @Pixel_5_API_31 &
          # echo '----------Show Devices--------------'
          # JAVA_HOME=$(/usr/libexec/java_home -v 1.8) $ANDROID_HOME/platform-tools/adb devices
