name: Build and Test iOS Application

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build_and_test:
    name: Build and Test iOS Application
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v3
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    - name: Build and Test Example App
      run: |
          xcodebuild test \
            -project TestApp.xcodeproj \
            -scheme TestApp \
            -destination 'name=iPhone 14 Pro Max' \
            -enableCodeCoverage YES \
            -resultBundlePath TestAppUITests.xcresult \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO
            sleep 300
    - name: Upload Artifact
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: TestAppUITests.xcresult
        path: TestAppUITests.xcresult
