# This is a basic workflow to help you get started with Actions
name: apt-test-ubuntu
# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - run: |
          sudo apt update
          sudo cat /etc/apt/sources.list
          echo *****************************************
          sudo ls -l /etc/apt/sources.list.d
          echo *****************************************
          sudo cat /etc/apt/sources.list.d/git-core-ubuntu-ppa-focal.list
          echo *****************************************
          sudo cat /etc/apt/sources.list.d/git-core-ubuntu-ppa-focal.list.save
          echo *****************************************
          sudo cat /etc/apt/sources.list.d/github_git-lfs.list.save
          echo *****************************************
          sudo cat /etc/apt/sources.list.d/microsoft-prod.list
          echo *****************************************
          sudo cat /etc/apt/sources.list.d/microsoft-prod.list.save
          echo *****************************************
          sudo cat /etc/apt/sources.list.d/ubuntu-toolchain-r-ubuntu-test-focal.list
          echo *****************************************
          sudo cat /etc/apt/sources.list.d/ubuntu-toolchain-r-ubuntu-test-focal.list.save
          pwd
        
