# This is a basic workflow to help you get started with Actions
name: test
# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  build:
   runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
   steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      # sudo apt-get install libz1 libncurses5 libbz2-1.0:i386 libstdc++6 libbz2-1.0
      # Runs a set of commands using the runners shell
      - name: Run a multiple lines
        run: |
          sudo apt-get install libpulse0:i386
          find /usr -name 'libpulse*'
