# This is a basic workflow to help you get started with Actions
name: apt-test-ubuntu
# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-22
    steps:
      - run: |
          sudo apt -y update
          cat /etc/apt/sources.list
          echo *****************************************
          ls -l /etc/apt/sources.list.d
          echo *****************************************
          cat /etc/apt/sources.list.d/git-core-ubuntu-ppa-focal.list
          echo *****************************************
          cat /etc/apt/sources.list.d/git-core-ubuntu-ppa-focal.list.save
          echo *****************************************
          cat /etc/apt/sources.list.d/github_git-lfs.list.save
          echo *****************************************
          cat /etc/apt/sources.list.d/microsoft-prod.list
          echo *****************************************
          cat /etc/apt/sources.list.d/microsoft-prod.list.save
          echo *****************************************
          cat /etc/apt/sources.list.d/ubuntu-toolchain-r-ubuntu-test-focal.list
          echo *****************************************
          cat /etc/apt/sources.list.d/ubuntu-toolchain-r-ubuntu-test-focal.list.save
          sudo find / -type f -name 'helpers'
          #cd imagegeneration/helpers/
          #sudo cat imagegeneration/helpers/apt-sources.txt
          pwd
        
