- job: Build
  pool:
      name: 'Azure Pipelines'
      vmImage: windows-2019
      steps:

- task: UseDotNet@2
  displayName: 'Use .Net 6.0'
   inputs:
        packageType: 'sdk'
        version: '6.0.x'
