name: List Win env

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
        
    - name: PowerShell lines run
      shell: pwsh
      run: |
        gci env:* | sort-object name
