# This is a basic workflow to help you get started with Actions
name: CI
# Controls when the workflow will run
on: [push]
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on:  windows-2022

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Run a multi-line script
        shell: cmd
        run: |
          attrib "C:\Program Files (x86)\Microsoft Visual Studio\Installer\setup.exe"
          "C:\Program Files (x86)\Microsoft Visual Studio\Installer\setup.exe" modify --add "Microsoft.VisualStudio.Component.WinXP" --installpath="C:\Program Files\Microsoft Visual Studio\2022\Enterprise" --quiet 
           dir C:\ProgramData\Microsoft\VisualStudio\Packages
