name: CI

on: [push]

jobs:
  macos:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - name: install yq
        run: |
          brew install yq
      - name: test yq
        run: |
         function Take-Part {
         param (
         [Parameter(ValueFromPipeline)]
         [string] $toolOutput,
         [string] $Delimiter = " ",
         [int[]] $Part
         )
         $parts = $toolOutput.Split($Delimiter, [System.StringSplitOptions]::RemoveEmptyEntries)
         $selectedParts = $parts[$Part]
         return [string]::Join($Delimiter, $selectedParts)
         }
         
         function Run-Command {
         param (
         [Parameter(Mandatory=$true)]
         [string] $Command,
         [switch] $SuppressStderr
         )
         # Bash trick to suppress and show error output because some commands write to stderr (for example, "python --version")
         $redirectOutputArguments = If ($SuppressStderr) { "2> /dev/null" } Else { "2>&1" }
         $stdout = & bash -c "${Command} ${redirectOutputArguments}"

         return $stdout
         }
         function Get-YqVersion {
         $yqVersion = Run-Command "yq --version" | Take-Part -Part 3
         return "YQ $yqVersion"
         }
         Write-Output "YQ $yqVersion"
        shell: pwsh
